### ISSUE TITLE
Alt attributes help specify alternative text

### ISSUE THREAD

**Issue by ghost** [somair/dasmoto_project#2]
https://github.com/somair/dasmoto_project/blob/8ac1793346e750babef528a31ed60db993d8866b/index.html#L14

Consider adding alt attributes to your images. They specify alternative test when an image cannot be displayed. An example is:

`<img src="dog.gif" alt="Image of a dog">`

**Comment by somair** [comment]
I just added alt attributes, and pushed up the updated code. Thank you
